batch_size: 32
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.001
lr_topo: 0.001
model_params:
  in_channels: 1
  num_classes: 10
  
  # ECLayr params
  t_const: True
  sublevel: False
  size:
  - 28
  - 28
  interval:
  - 0.7
  - 1
  steps: 32
  gtheta_cfg:
  - 32
  - 32
  beta: 0.01
sch_patience: 10
threshold: 0.001