batch_size: 16
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.0001
model_params:
  bump_steps: 32
  ect_type: "faces"
  num_classes: 10
  num_features: 3
  num_thetas: 32
  R: 1.1
sch_patience: 10
threshold: 0.001