batch_size: 16
epochs: 1000
es_patience: 25
factor: 0.1
lr_conv: 0.0001
lr_fc: 0.0001
lr_topo: 0.0005
lr_topo_2: 0.0005
model_params:
  # as_vertices: True
  as_vertices: False
  hidden_features:
  # - 64
  - 32
  in_channels: 1
  interval_1:
  - 0
  - 7
  - 32
  interval_2:
  - 1
  - 8
  - 32
  interval_3:
  - -8
  - 0
  - 32
  num_classes: 10
  size:
  - 28
  - 28
  sublevel: True
sch_patience: 10
threshold: 0.001
