batch_size: 32
epochs: 1000
es_patience: 10
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 10
  # ECLayr params
  interval:
  - 0.06
  - 0.3
  steps: 32
  constr: "V"
  sublevel: True
threshold: 0.001