batch_size: 32
epochs: 1000
es_patience: 10
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 10
  # ECLayr params
  interval_1:
  - 0.02
  - 0.075
  interval_2:
  - 0.05
  - 0.5
  steps: 32
  constr: "V"
  sublevel_1: True
  sublevel_2: False
  # beta: 0.01
  beta: 0.1
threshold: 0.001