batch_size: 16
epochs: 100
es_patience: 3
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 10
  # ECLayr params
  interval_1:
  - 0.05
  - 0.09
  interval_2:
  - 0.05
  - 0.5
  steps_1: 25
  steps_2: 18
  constr: "V"
  sublevel_1: True
  sublevel_2: False
  beta: 0.01
threshold: 0.003