batch_size: 16
epochs: 1000
es_patience: 25
factor: 0.1
lr_conv: 0.0001
lr_fc: 0.0001
# lr_topo: 0.005
lr_topo: 0.1
model_params:
  hidden_features:
  - 32
  in_channels: 1
  num_classes: 10
sch_patience: 10
threshold: 0.001
