batch_size: 16
epochs: 1000
es_patience: 25
factor: 0.1
lr_conv: 0.0001
lr_fc: 0.0001
lr_topo: 0.1
lr_topo_2: 0.001
model_params:
  as_vertices: False
  dimensions:
  - 0
  - 1
  hidden_features:
  - 32
  in_channels: 1
  interval:
  - -7
  - 0
  K_max: 2
  num_classes: 10
  steps: 32
  sublevel: False
sch_patience: 10
threshold: 0.001