batch_size: 32
epochs: 1000
es_patience: 10
lr: 0.001
model_params:
  num_classes: 5
  # Pllay params
  interval:
  - 0.03
  - 0.1
  steps: 32
  constr: "V"
  sublevel: True
  KK:
  - 0
  - 1
  grid_size:
  - 40
  - 40
  dimensions:
  - 0
  - 1
threshold: 0.001