batch_size: 32
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.001
# lr_conv: 0.0001
# lr_fc: 0.0001
lr_topo: 0.0001
model_params:
  in_channels: 3
  num_classes: 10
  
  # ECLayr params
  t_const: False
  sublevel: False
  size:
  - 32
  - 32
  interval:
  - 0
  - 1
  steps: 32
  gtheta_cfg:
  - 32
  - 16
  beta: 0.3   # subject to change
sch_patience: 10
threshold: 0.001