batch_size: 32
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.001
lr_topo: 0.0001
# lr_conv: 0.0001
# lr_fc: 0.0001
# lr_topo: 0.0005
model_params:
  in_channels: 3
  num_classes: 10
  
  # ECLayr params
  t_const: True
  sublevel: False
  size:
  - 32
  - 32
  interval:
  - 0
  - 1
  steps: 64
  gtheta_cfg:
  - 64
  - 32
sch_patience: 10
threshold: 0.001