batch_size: 32
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.001
lr_topo: 0.0001
model_params:
  in_channels: 1
  num_classes: 10

  # ECLayr params
  t_const: False
  sublevel: True
  size:
  - 28
  - 28
  interval_1:
  - 0.06
  - 0.3
  interval_2:
  - 0.14
  - 0.4
  steps: 64
  gtheta_cfg:
  - 64
  - 32
sch_patience: 10
threshold: 0.001
