batch_size: 32
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.001
lr_topo: 0.001
model_params:
  in_channels: 1
  num_classes: 10

  # ECLayr params
  t_const: True
  sublevel_1: True
  sublevel_2: False
  size_1:
  - 28
  - 28
  size_2:
  - 26
  - 26
  interval_1:
  - 0.03
  - 0.34
  interval_2:
  - 0.06
  - 0.35
  interval_3:
  - 0
  - 1
  steps: 32
  gtheta_cfg:
  - 32
  - 32
  beta: 0.001
sch_patience: 10
threshold: 0.001