batch_size: 16
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.01
model_params:
  K_max: 2
  dimensions:
  - 0
  - 1
  hidden_features:
  - 32
  in_channels: 1
  lims:
  - - 1
    - 28
  - - 1
    - 28
  m0: 0.05
  num_classes: 10
  r: 2
  size:
  - 28
  - 28
  tseq:
  - 0
  - 1
  - 32
  use_dtm: false
sch_patience: 10
threshold: 0.001
