batch_size: 16
epochs: 1000
es_patience: 25
factor: 0.1
lr_fc: 0.001
lr_res: 0.005
lr_topo: 0.01
lr_topo2: 0.01
model_params:
  as_vertices: False
  block_cfg:
  - 2
  - 2
  - 2
  - 2
  dimensions:
  - 0
  - 1
  filter_cfg:
  - 64
  - 128
  - 256
  - 512
  hidden_features:
  - 64
  - 32
  in_channels: 1
  interval:
  - -2.5
  - -0
  K_max: 2
  num_classes: 10
  steps: 32
  sublevel: False
sch_patience: 10
threshold: 0.001
