batch_size: 64
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.01
lr_topo: 0.0001
model_params:
  # ResNet params
  in_channels: 1
  num_classes: 2
  block_cfg:
  - 2
  - 2
  - 2
  - 2
  filter_cfg:
  - 64
  - 128
  - 256
  - 512

  # ECLayr params
  t_const: False
  sublevel: False
  size:
  - 112
  - 112
  interval:
  - 0.4
  - 1
  steps: 64
  gtheta_cfg:
  - 64
  - 64
sch_patience: 10
threshold: 0.001