batch_size: 64
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.01
lr_topo: 0.0001
model_params:
  # ResNet params
  in_channels: 1
  num_classes: 2
  block_cfg:
  - 2
  - 2
  - 2
  - 2
  filter_cfg:
  - 64
  - 128
  - 256
  - 512

  #ECLayr params
  t_const: False
  sublevel: False
  size_one:
  - 112
  - 112
  size_two:
  - 28
  - 28
  interval_one:
  - 0.4
  - 1
  interval_two:
  - 0.3
  - 1
  steps: 64
  gtheta_cfg:
  - 64
  - 64
  beta: 0.01
sch_patience: 10
threshold: 0.001