batch_size: 16
epochs: 100
es_patience: 3
lr: 0.001
model_params:
  num_classes: 10
  # Pllay params
  interval:
  - 0.06
  - 0.3
  steps: 25
  constr: "V"
  sublevel: True
  KK:
  - 0
  - 1
  grid_size:
  - 28
  - 28
  dimensions:
  - 0
  - 1
threshold: 0.003