batch_size: 32
epochs: 1000
es_patience: 10
lr: 0.001
model_params:
  num_classes: 10
  # Pllay params
  interval_1:
  - 0.025
  - 0.07
  interval_2:
  - 0.1
  - 0.45
  steps: 32
  constr: "V"
  sublevel_1: True
  sublevel_2: False
  KK:
  - 0
  - 1
  grid_size:
  - 28
  - 28
  dimensions:
  - 0
  - 1
threshold: 0.001