batch_size: 32
epochs: 1000
es_patience: 25
factor: 0.1
lr: 0.001
model_params:
  num_classes: 10
  
  # Pllay params
  t_const: True
  sublevel: True
  dimensions:
  - 0
  - 1
  grid_size:
  - 28
  - 28
  interval_one:
  - 0.02
  - 0.28
  interval_two:
  - 0.06
  - 0.29
  KK:
  - 0
  - 1
  steps: 32
  out_features: 32
sch_patience: 10
threshold: 0.001