batch_size: 32
epochs: 100
es_patience: 10
lr: 0.001
model_params:
  num_classes: 10
  # Pllay params
  interval_1:
  - 0.06
  - 0.3
  interval_2:
  - 0.05
  - 0.95
  steps_1: 32
  steps_2: 32
  constr: "V"
  sublevel_1: True
  sublevel_2: False
  KK:
  - 0
  - 1
  grid_size:
  - 28
  - 28
  dimensions:
  - 0
  - 1
threshold: 0.001