batch_size: 16
epochs: 100
es_patience: 3
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 5
  # ECLayr params
  interval_1:
  - 0.03
  - 0.1
  interval_2:
  - 0.05
  - 0.95
  steps_1: 17
  steps_2: 18
  constr: "V"
  sublevel_1: True
  sublevel_2: False
  beta: 0.02
threshold: 0.003