batch_size: 16
epochs: 1000
es_patience: 3
factor: 0.1
lr: 0.001
lr_topo: 0.001
model_params:
  in_channels: 1
  num_classes: 5

  # ECLayr params
  t_const: True
  sublevel: True
  size:
  - 40
  - 40
  interval:
  - 0.03
  - 0.1
  steps: 17
  gtheta_cfg:
  - 17
  - 64
sch_patience: 10
threshold: 0.001
