batch_size: 16
epochs: 1000
es_patience: 3
factor: 0.1
lr: 0.001
lr_topo: 0.001
model_params:
  in_channels: 1
  num_classes: 5

  # ECLayr params
  t_const: True
  sublevel: True
  size:
  - 40
  - 40
  interval_one:
  - 0.03
  - 0.1
  interval_two:
  - 0.05
  - 0.95
  steps_one: 17
  steps_two: 18
  gtheta_cfg_one:
  - 17
  - 64
  gtheta_cfg_two:
  - 18
  - 64
  beta: 0.1
sch_patience: 10
threshold: 0.001
