batch_size: 16
epochs: 100
es_patience: 3
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 5
  # ECLayr params
  interval:
  - 0.03
  - 0.1
  steps: 32
  constr: "V"
  sublevel: True
threshold: 0.003